# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ver√≥nica Hurtado Lozada
tagline:          'UBC PhD candidate'
description:      ''
baseurl:          /hyde/

author:
  name:           ''
  url:            https://twitter.com/verohurtado_

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
